name: Release

on:
  push:
    tags:
      - "release-*"

jobs:
  release:
    runs-on: ubuntu-latest
    name: Publish
    env:
      HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - uses: erlef/setup-beam@v1
        name: Install Erlang and Elixir
        id: setup-beam
        with:
          version-file: .tool-versions
          version-type: strict

      - name: Fetch dependencies
        run: mix deps.get

      - name: Publish
        run: mix hex.publish --yes
