name: Release

on:
  push:
    tags:
      - "release-*"

jobs:
  release:
    runs-on: ubuntu-latest
    name: Publish
    env:
      HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - uses: erlef/setup-beam@v1
        name: Install Erlang and Elixir
        id: setup-beam
        with:
          version-file: .tool-versions
          version-type: strict

      - name: Cache deps
        id: cache-deps
        uses: actions/cache@v4
        env:
          cache-name: cache-elixir-deps
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ env.cache-name }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-${{ env.cache-name }}-


      - name: Restore dependencies cache
        uses: actions/cache@v4
        with:
          path: deps
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-release-deps-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-release-deps-${{ hashFiles('**/mix.lock') }}
            ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-release-deps
      
      - name: Fetch dependencies
        run: mix deps.get

      - name: Publish
        run: mix hex.publish --yes
